version: "2"
services:
  flaskde:
    build: ./flaskde
    image: flaskde
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"
        
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro 
